### ISSUE TITLE
filings.save does not always select the company CIK

### ISSUE THREAD

**Issue by iamjeroen** [coyo8/sec-edgar#100]
**Describe the bug**
`cik = doc_name.split('-')[0]` selects the first part of the accession number. According to the SEC documentation this is a CIK but not always the CIK of the company as [explained here](https://www.sec.gov/about/webmaster-faq.htm#accession-number). This may lead to unexpected directories upon saving

**To Reproduce**
1. For example download and save latest 10-K filing of Abbott Laboratories (ticker=ABT, CIK=1800)
2. The url to this filing is constructed as 
`https://www.sec.gov/Archives/edgar/data/1800/000110465920023904/0001104659-20-023904.txt`
3. Notice the first part of the Accession Number is different from the CIK of the company

**Additional context**
Name: secedgar
Version: 0.1.5

**Comment by iamjeroen** [comment]
Suggested change:
`cik = url.split('/')[6].zfill(10)`

**Comment by jackmoody11** [comment]
> Suggested change:
> `cik = url.split('/')[6].zfill(10)`

Not sure if the beginning will every change but would it be ok if we did `cik = url.split('/')[-3].zfill(10)` instead?

**Comment by jackmoody11** [comment]
> **Describe the bug**
> `cik = doc_name.split('-')[0]` selects the first part of the accession number. According to the SEC documentation this is a CIK but not always the CIK of the company as [explained here](https://www.sec.gov/about/webmaster-faq.htm#accession-number). This may lead to unexpected directories upon saving
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. For example download and save latest 10-K filing of Abbott Laboratories (ticker=ABT, CIK=1800)
> 2. The url to this filing is constructed as
>    `https://www.sec.gov/Archives/edgar/data/1800/000110465920023904/0001104659-20-023904.txt`
> 3. Notice the first part of the Accession Number is different from the CIK of the company
> 
> **Additional context**
> Name: secedgar
> Version: 0.1.5

Good catch! Thank you for bring this to our attention. Will you see if my proposed change (in response to yours) will work and let me know?

**Comment by iamjeroen** [comment]
> > Suggested change:
> > `cik = url.split('/')[6].zfill(10)`
> 
> Not sure if the beginning will every change but would it be ok if we did `cik = url.split('/')[-3].zfill(10)` instead?

Not sure if the ending will ever change either, so both could work for now.

Perhaps a more structural solution would be doing something with the list of CIKs already available in the class? Like have get_urls() return a dictionary {cik:url} instead of a list.
