### ISSUE TITLE
Make unit test for the project

### ISSUE THREAD

**Issue by coyo8** [coyo8/sec-edgar#2]
Currently, there is no Unit test for the project. Add test for filings and saving to directories check for each of the requests.

**Comment by jackmoody11** [comment]
1. We can add a test to detect whether the directory are created or not?
2. We can mock request and response basically fetch_report method
3. Also the sanitize_date method.
4. Also some manipulations on the URL. As this crawler is too dependent on the string URL.

**Comment by jackmoody11** [comment]
I am going to close this issue and open up more specific issues related to testing so that we can better track what tests need to be added.
