### ISSUE TITLE
Substituting '-index.html' to 'txt' doesn't work now

### ISSUE THREAD

**Issue by yunjianyang** [coyo8/sec-edgar#20]
Hi all,

For recent 10-K files, this mechanism doesn't work. It works for AAPL 2001 but not for 2017.

**Comment by HiramRuiz** [comment]
Hey everyone, first I have to say im a total noob.

I am also getting an issue with recent statements. Tried with APPL and PM and the files I end up with are formatted wierdly. 

Output looks like:
`<P STYLE="margin-top:0px;margin-bottom:0px" ALIGN="center"><FONT STYLE="font-family:Times New Roman" SIZE="2">UNITED STATES </FONT></P> <P STYLE="margin-top:0px;margin-bottom:0px" ALIGN="center"><FONT
STYLE="font-family:Times New Roman" SIZE="2">SECURITIES AND EXCHANGE COMMISSION </FONT></P> <P STYLE="margin-top:0px;margin-bottom:0px" ALIGN="center"><FONT STYLE="font-family:Times New Roman" SIZE="2">WASHINGTON, D.C. 20549 </FONT></P>
<P STYLE="margin-top:0px;margin-bottom:0px" ALIGN="center"><FONT STYLE="font-family:Times New Roman" SIZE="2">FORM 10-Q </FONT></P> <P STYLE="margin-top:6px;margin-bottom:0px"><FONT STYLE="font-family:Times New Roman" SIZE="2">(Mark One) </FONT></P>
<P STYLE="font-size:12px;margin-top:0px;margin-bottom:0px">&nbsp;</P>
<TABLE STYLE="BORDER-COLLAPSE:COLLAPSE" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">
<TR>
<TD WIDTH="8%" VALIGN="top" ALIGN="left"><FONT STYLE="font-family:Times New Roman" SIZE="2">(X)</FONT></TD>
<TD ALIGN="left" VALIGN="top"> <P ALIGN="justify"><FONT STYLE="font-family:Times New Roman" SIZE="2">QUARTERLY REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 </FONT></P></TD></TR></TABLE>
<P STYLE="margin-top:12px;margin-bottom:0px" ALIGN="center"><FONT STYLE="font-family:Times New Roman" SIZE="2">For the quarterly period ended September&nbsp;30, 2011 </FONT></P> <P STYLE="margin-top:12px;margin-bottom:0px" ALIGN="center"><FONT
STYLE="font-family:Times New Roman" SIZE="2">OR </FONT></P> <P STYLE="font-size:12px;margin-top:0px;margin-bottom:0px">&nbsp;</P>
<TABLE STYLE="BORDER-COLLAPSE:COLLAPSE" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">
<TR>
<TD WIDTH="8%" VALIGN="top" ALIGN="left"><FONT STYLE="font-family:Times New Roman" SIZE="2">(&nbsp;&nbsp;)</FONT></TD>
<TD ALIGN="left" VALIGN="top"> <P ALIGN="justify"><FONT STYLE="font-family:Times New Roman" SIZE="2">TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934 </FONT></P></TD></TR></TABLE>
<P STYLE="margin-top:12px;margin-bottom:0px"><FONT STYLE="font-family:Times New Roman" SIZE="2">For the transition period from &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
to &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </FONT></P>
<P STYLE="margin-top:12px;margin-bottom:0px" ALIGN="center"><FONT STYLE="font-family:Times New Roman" SIZE="2">Commission File Number 001-33708 </FONT></P> <P STYLE="margin-top:12px;margin-bottom:0px" ALIGN="center"><FONT
STYLE="font-family:Times New Roman" SIZE="2">Philip Morris International Inc.</FONT></P> <P STYLE="line-height:3px;margin-top:0px;margin-bottom:2px;border-bottom:0.5pt solid #000000">&nbsp;</P>
<P STYLE="margin-top:0px;margin-bottom:0px" ALIGN="center"><FONT STYLE="font-family:Times New Roman" SIZE="2">(Exact name of registrant as specified in its charter) </FONT></P> <P STYLE="font-size:12px;margin-top:0px;margin-bottom:0px">&nbsp;</P>
<TABLE CELLSPACING="0" CELLPADDING="0" WIDTH="100%" BORDER="0" STYLE="BORDER-COLLAPSE:COLLAPSE" ALIGN="center">`

**Comment by coyo8** [comment]
I will check out this and fix it.

**Comment by jackmoody11** [comment]
@yunjianyang have you tried working with the most recent version (0.1.4)? Now it should work. I did note when using a later date for AAPL that the documents were out of order, but the documents were still downloaded.

**Comment by jackmoody11** [comment]
Using the following should work:

```python
from SECEdgar.crawler import SecCrawler

crawler = SecCrawler()
crawler.filing_10K('AAPL', '0000320193', '20190101', '10') 
```

**Comment by yunjianyang** [comment]
Thank you. I'll try it later.
