### ISSUE TITLE
No file download, running the tutorial code. This library did not work

### ISSUE THREAD

**Issue by liwzhi** [coyo8/sec-edgar#23]
I have installed this library through pip. 

And, running the tutorial code, it did not work, no files in my local computer.

**Comment by scigeek72** [comment]
Same problem....no files downloaded.

**Comment by vijaydwivedi75** [comment]
Did you find any library which works to download SEC filings?

**Comment by bag189** [comment]
same issues. I ran tutorial code and received 

from SECEdgar.crawler import SecCrawler
secCrawler = SecCrawler()
secCrawler.filing_10K('AVB', '0000915912', '20101231', '8')

started !0-KAVB
('Number of files to download %s', 10)
Starting download....
Not able to save the file :( 
Successfully downloaded all the files

The folder was created, but nothing in it

**Comment by coyo8** [comment]
@liwzhi @scigeek72 @bag189 I haven't updated the pip library for very long. Can you use the github version. You can download using.

```
$ pip install https://github.com/coyo8/sec-edgar/archive/master.zip

```
if still, this issue persists let me know; will add proper support for it in next release.

**Comment by genelll** [comment]
Same result using version 1.4 "Not able to save the file :("

**Comment by jackmoody11** [comment]
Thanks for adding the error trace. I won’t be able to work on this for a few days, but it looks like the setup.py file needs to be modified to fix how requirements are read. If nobody else can pick this up, I can in a week.

**Comment by jackmoody11** [comment]
@genelll I have added a MANIFEST.in file which should include the requirements file. I am going to close this issue as everything seems to be working properly now. Let me know if the problem persists and thanks for helping us out!
