### ISSUE TITLE
Add APIs for more filing types

### ISSUE THREAD

**Issue by coyo8** [coyo8/sec-edgar#3]
currently it supports only for four i.e. 10K, 10Q, 8K, 13F

**Comment by coyo8** [comment]
@jackmoody11 do you have any ideas about which filings are important apart from above four we can add support for them?

**Comment by jackmoody11** [comment]
Looking through recent reports for Apple, here are some that seem to come up:

- **424B2**: Forms for prospectuses
- **DEF 14A**: Definitive proxy statements
- **SC 13G**: Statement of acquisition of beneficial ownership by individuals
- **SC 13G/A**: Amendment to SC 13G
- **8-A12B**: Registration of securities
- **25**: Notification of the removal from listing and registration of matured, redeemed or retired securities
- **S-8**: Securities to be offered to employees in employee benefit plans

I think it would be fine to add each of these (as it should only be a few lines of code for each report); however, if we are going to start adding parsing support, we should probably prioritize reports such as the 10-K and 10-Q before those listed above.

**Comment by coyo8** [comment]
Cool. Parsing has been in my mind for very long. We will have to do a little bit planning for it. I will add my insights in the WIKI for the parsing. We can move forward from there then. 

I will check if these filings are easy to add meaning we need to test each one of it and so it will require quite an amount of time. If things goes good; I will add it.

**Comment by jackmoody11** [comment]
A more complete answer to the available forms can be found at [sec.gov/forms](https://www.sec.gov/forms)

**Comment by jackmoody11** [comment]
I vote to close this issue as it should be a matter of changing `_VALID_FILING_TYPES`. Do you agree @coyo8?

**Comment by jackmoody11** [comment]
This should be taken care of with FilingType enum
