### ISSUE TITLE
Instead of using a huge single class; modularise the code.

### ISSUE THREAD

**Issue by coyo8** [coyo8/sec-edgar#32]
Currently, one Single class handles all the responsibilities which are not good for a codebase as it makes changing things difficult and can cause many bugs and failure.

I will design a basic architecture which is abstract away some of the responsibility.

**Comment by jackmoody11** [comment]
This is in progress. You can see my progress on the *modularize* branch [here](https://github.com/jackmoody11/sec-edgar/blob/modularize/SECEdgar/filings.py). Feel free to make PRs as needed, and I will hopefully be able to merge this into master soon.
