### ISSUE TITLE
Programmatically Resolve CIK Codes

### ISSUE THREAD

**Issue by cancan101** [coyo8/sec-edgar#4]
See discussion: http://quant.stackexchange.com/questions/8099/central-index-key-cik-of-all-traded-stocks

**Comment by rahulrrixe** [comment]
@cancan101 do you want CIK code of a company can be resolved with its company code or name?

like providing 'AAPL' or  'Apple Inc' can resolve its CIK to 0000320193.

**Comment by cancan101** [comment]
Ideally would be to specify the ticker but tickers are not reliably unique across time. That being said the SEC does have some of this functionality on the EDGAR site: [AAPL](https://www.sec.gov/cgi-bin/browse-edgar?CIK=AAPL&Find=Search&action=getcompany).

This might be scope creep, but would be cool to have some API to wrap the CIK mapping. ie some way of getting what ever the SEC has.

**Comment by coyo8** [comment]
Long time but will take this issue.

**Comment by coyo8** [comment]
There is an already WIP for this feature  #18; I am investigating more option about it to finalize the support.

**Comment by jackmoody11** [comment]
The latest PR should address this. Will close once that is approved.

**Comment by jackmoody11** [comment]
This issue has been moved to #81
