### ISSUE TITLE
Fetching more than 100 documents

### ISSUE THREAD

**Issue by jackmoody11** [coyo8/sec-edgar#44]
Our current method of fetching urls to use for downloading the reports as txt files limits the number of files that can be downloaded to 100. It would be better to handle pagination so that we can exceed this limit if desired.

I think #10 is relevant here. Users should be able to download a certain number of files other than the default options of 10, 20, 40, 80, and 100.

Thanks to @mdalisouayah for pointing this out.

**Comment by jackmoody11** [comment]
This is currently in progress

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdalisouayah** [comment]
Thank you Jack. Your scraper was instrumental to my project. I did not miss
to reference your work! Thanks again.

**Comment by jackmoody11** [comment]
@mdalisouayah glad it helped!
