### ISSUE TITLE
Add doctr for automatically deploying docs. Will need help from @coyo8 for this.

### ISSUE THREAD

**Issue by jackmoody11** [coyo8/sec-edgar#55]

**Comment by jackmoody11** [comment]
Using [doctr](https://drdoctr.github.io) will allow us to automate our documentation deployment when using GitHub Pages.

**Comment by jackmoody11** [comment]
@coyo8 According to the last build by Travis, this doesn't seem to be working properly. You may need to run `doctr configure` again or it may be a problem with us not having a gh-pages branch. Will you try doing these two things and see if that fixes the issue?

**Comment by coyo8** [comment]
It is working and got published at http://www.rudrakos.com/sec-edgar/. Due to my custom domain configuration; it is getting published on my personal blog domain. I will look into how to change that.

**Comment by jackmoody11** [comment]
Everything looks good. I don't think there is any reason to change the domain as long as we link to it in the description.
