### ISSUE TITLE
Idea: Change SECEdgar folder to secedgar

### ISSUE THREAD

**Issue by jackmoody11** [coyo8/sec-edgar#57]
**Is your feature request related to a problem? Please describe.**
It is normally recommended that package names are lowercase.

**Describe the solution you'd like**
Consider changing the folder <kbd>SECEdgar</kbd> to <kbd>secedgar</kbd> if it doesn't cause any breaks in functionality.

**Comment by jackmoody11** [comment]
@coyo8 what are your thoughts on this?

**Comment by chrjxj** [comment]
support jack's suggestion.
