### ISSUE TITLE
How to extract data from file?

### ISSUE THREAD

**Issue by raffam** [coyo8/sec-edgar#60]
This is not a bug report but a request from help. How to extract the data from the .txt filing?
For example, I got the attached .txt file, which seems to embed a PDF file in turn. How can I extract the PDf file from this txt file?
[0000000000-15-011167.txt](https://github.com/coyo8/sec-edgar/files/3271609/0000000000-15-011167.txt)

**Comment by jackmoody11** [comment]
How did you get this result? It looks like it is encoded. It might need to be decoded.

**Comment by raffam** [comment]
Yeah it is uuencoded but I solved it with the extractor
