### ISSUE TITLE
Latest pypi distribution does not include filings module

### ISSUE THREAD

**Issue by ethanjahn** [coyo8/sec-edgar#64]
**Describe the bug**
Installing latest version using pip does not include the filings module, which appears to contain the preferred class according to the documentation

**To Reproduce**
1. Run `pip install SECEdgar` or `pip install SECEdgar==0.1.4`
2. Attempt to import to python using `import SECEdgar.filings`
3. See `ModuleNotFoundError: No module named SECEdgar.filings`

**Expected behavior**
Filings module installed with pip installation or documentation suggesting filings module is experimental

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 0.1.4

**Additional context**
If the filings module is not ready for release, it would be helpful for the documentation to suggest using the crawler until v0.1.5

**Comment by raffam** [comment]
I think you have to use the Github version for this

**Comment by jackmoody11** [comment]
@ethanjahn @raffam's comment is correct. This functionality is only available in v0.1.5. I will submit a change to the documentation and README.
