### ISSUE TITLE
Help! - Not able to save the file :( error

### ISSUE THREAD

**Issue by ericzx** [coyo8/sec-edgar#7]
Hi,

I've implemented everything correctly but I get a "Not able to save the file :(" error. I see the appropriate SEC-edgar-data directory being created with the ticker/file sub-directory but it's empty/no file.

It returns "Successfully downloaded all the files" but I guess something is preventing it from saving?
Any ideas on what could be going wrong? 
Any help would be appreciated! Thanks!

**Comment by rahulrrixe** [comment]
@ericzx If you have downloaded the project from pypy (which is not updated) then you might be getting above error but if you try to install the project from the github then it will work the way it supposed to.

**Comment by ericzx** [comment]
Thanks for getting back!

Yes I was using the pypy version. So I manually uninstalled that version and re-installed it via pip, but I still get the same error. Here is the command output:

Python 2.7.2 (default, Jun 12 2011, 14:24:46) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> from SECEdgar.crawler import SecCrawler
>>> secCrawler=SecCrawler()
>>> secCrawler.filing_10K('AAPL', '0000320193', '20010101', '10')
started !0-KAAPL
C:\Python27\lib\site-packages\bs4\__init__.py:166: UserWarning: No parser was ex
plicitly specified, so I'm using the best available HTML parser for this system
("html.parser"). This usually isn't a problem, but if you run this code on anoth
er system, or in a different virtual environment, it may use a different parser
and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
('Number of files to download %s', 8)
Starting download....
Not able to save the file :(
Successfully downloaded all the files
>>>

...

And I see the directory being created, but no file. Would this have anything to do with the error prompted above? Sorry I'm still a noob at Python, but when it says  change : BeautifulSoup([your markup]) to this: BeautifulSoup([your markup], "html.parser") ... where am I supposed to do this?

Or ... is it maybe that there are no filings for the requested date (being 20010101)? 
Since companies don't file 10-Ks every single day, should I try it with a date consistent with the official filing/release date of an actual 10-K filing?

Thanks!

**Comment by hamm44** [comment]
Hi,

I have the exact same issue with unable to save the file.

I am using os x and have downloaded the package from github link.

I am also getting an error message similar to ericzx

    /usr/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

    To get rid of this warning, change this:

     BeautifulSoup([your markup])

    to this:

     BeautifulSoup([your markup], "lxml")

**Comment by rahulrrixe** [comment]
@hamm44 @ericzx  Use the github instance, the project available on pypy have some issues. To install try below commands
<code> pip install git+https://github.com/rahulrrixe/SEC-Edgar </code> 
Hope this might fixes your proble. If not, let me know.

**Comment by hamm44** [comment]
I tried using the the github instance, but it is still showing the same unable to save file error.

**Comment by rahulrrixe** [comment]
@hamm44 I will fix the problem in next few days and will update you.

**Comment by mountainhilljill** [comment]
@rahulrrixe hi, I also tried using the github instance and got the same result with @hamm44 .NOT able to save file error. Have you fix this already? Thanks

**Comment by rahulrrixe** [comment]
@mountainhilljill @hamm44 @ericzx This issue has been fixed today using #8. You can fetch or clone the update code and run it.

**Comment by mountainhilljill** [comment]
@rahulrrixe Thanks,it works!!!

**Comment by Keni1989** [comment]
@rahulrrixe: Hi, first, thank you very much for the opportunity to use your script. I also tried to implement the updated one but in my case, it did not save the 10-K/10-Q etc. For Instance by using the following comand in Python Shell: 
>>> secCrawler.filing_10K('MSFT', '0000789019', '20140101', '10')
the output is:

`started !0-KMSFT
('Number of files to download %s', 10)
Starting download....
Not able to save the file :( 
Successfully downloaded all the files`

Then I see the Folder "SEC-Edgar-data\MSFT\0000789019\filing_type" but I am not able to save the files from the EDGAR homepage.

Do you know why it does not work?

Thank you very much for your help !

**Comment by rodrigosnader** [comment]
@Keni1989 same here.

**Comment by jackmoody11** [comment]
@rodrigosnader @Keni1989 are you using the most recent version of SECEdgar from GitHub? I can't reproduce this problem on my end. We are working on updating the PyPi release.

**Comment by coyo8** [comment]
We have updated the pypi.  can you try `pip install SECEdgar==0.1.4` installing the latest version and check if it works for you.

**Comment by genelll** [comment]
requirements.txt is missing, while attempting to install via pip install SECEdgar==0.1.4

**Comment by coyo8** [comment]
I will update it today.

**Comment by coyo8** [comment]
@genelll can you share the log here.

```
$ sudo pip install SECEdgar==0.1.4
Collecting SECEdgar==0.1.4
  Downloading https://files.pythonhosted.org/packages/8a/88/a6c2d1f2417f2eed1311bd192f178d4eb8be08d592acc557848e09e624bc/SECEdgar-0.1.4-py3-none-any.whl
Collecting future==0.13.1 (from SECEdgar==0.1.4)
Collecting beautifulsoup4==4.4.0 (from SECEdgar==0.1.4)
  Downloading https://files.pythonhosted.org/packages/63/05/e1b733dc34fce994954c06bd198486c1becc2839d64ac1747424d49e8a35/beautifulsoup4-4.4.0-py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 3.0MB/s
Requirement already satisfied: flake8 in /usr/local/lib/python3.6/site-packages (from SECEdgar==0.1.4)
....
....
Installing collected packages: future, beautifulsoup4, more-itertools, atomicwrites, attrs, pluggy, py, pytest, certifi, urllib3, chardet, idna, requests, SECEdgar
Successfully installed SECEdgar-0.1.4 atomicwrites-1.3.0 attrs-19.1.0 beautifulsoup4-4.4.0 certifi-2019.3.9 chardet-3.0.4 future-0.13.1 idna-2.8 more-itertools-7.0.0 pluggy-0.6.0 py-1.8.0 pytest-3.6.3 requests-2.21.0 urllib3-1.24.2
```

**Comment by jackmoody11** [comment]
>@genelll can you share the log here. ...

@coyo8 does pip install work without using sudo?

**Comment by coyo8** [comment]
@jackmoody11 not necessarily. I needed because it is my system python. Don't need it if it is `brew` or in `virtualenv`.

**Comment by jackmoody11** [comment]
>@jackmoody11 not necessarily. I needed because it is my system python. Don't need it if it is `brew` or in `virtualenv`.

@coyo8 ok that makes sense. Thanks!

**Comment by jackmoody11** [comment]
@genelll can you add the log as @coyo8 mentioned?

**Comment by jackmoody11** [comment]
@genelll @coyo8  I just realized that previous versions of this project did not include a MANIFEST.in file to tell PyPi to include the requirements.txt file. I have added a pull request which should fix this. I think it might be best to set up `tox` with this project so that we can do a better job of testing on a fresh environment in the future. I will open a new issue for that.

**Comment by jackmoody11** [comment]
This issue is a bit dated and I believe that recent changes (adding MANIFEST.in file) should fix the issue. If this issue persists, please open another issue and I will take a look at it.
