### ISSUE TITLE
Crawler downloads multiple times if count > number of filings

### ISSUE THREAD

**Issue by Alex6614** [coyo8/sec-edgar#75]
**Describe the bug**
I'm crawling for all 10-K filings of companies. When I set the count to above the number of actual 10-K filings, the crawler loops through the 10-K again and appends to the output file multiple times. This creates files that are multiples in length of what it should be

**To Reproduce**
1. Use cik=0001652044 for Google, which currently has 6 10-K filings
2. Run something like `my_filings = Filing(cik=cik, filing_type=filing_type, count=40)`
3. The output files are about 6-7 times the size they should be

**Expected behavior**
Either the crawler stops once it reaches the last file, or it loops again but does not append to the file.

**Desktop (please complete the following information):**
I'm running this on a Jupyter Notebook on Windows

**Additional context**
I think this can be fixed by changing line 89 in crawler.py to: `with open(path, "wb") as f:`, switching from the append ('ab') config to write ('wb') config.

**Comment by jackmoody11** [comment]
Should be closed with #77
