### ISSUE TITLE
from SECEdgar.filings import Filing() --> SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by studiocardo** [coyo8/sec-edgar#76]
**Describe the bug**

1. 
**To Reproduce**

1. #> pip install SECEdgar
2. #> python
3. >>> from SECEdgar.filings import Filing()
4.>>> 
  File "<stdin>", line 1
    from SECEdgar.filings import Filing()
                                       ^
SyntaxError: invalid syntax
>>> from SECEdgar.filings import Filing()
  File "<stdin>", line 1
    from SECEdgar.filings import Filing()
                                       ^
SyntaxError: invalid syntax
>>> 

1.a> pip uninstall SECedgar
2.a> git clone https://github.com/rahulrrixe/SEC-Edgar.git; cd SEC-Edgar/; py setup.py install
3.a> Finished processing dependencies for SECEdgar==0.1.5
 4.a > python
4.b >>> from SECEdgar.filings import Filing() --> SyntaxError: invalid syntax

It's broken...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
If specific to your OS, please specify which OS you are using [e.g. Windows, macOS, Ubuntu Linux, etc.]

**Additional context**

**Comment by huntersgordon** [comment]
Try this: 
`from SECEdgar.filings import Filing`
don't type parenthesis after Filing
