### ISSUE TITLE
Form 8K Not Supported in Version 0.1.5?

### ISSUE THREAD

**Issue by mksamelson** [coyo8/sec-edgar#88]
I don't see Forms 8-K among the supported forms in Filings.  Is that right?  Am I missing something?

Thanks

**Comment by jackmoody11** [comment]
You are right. Thanks for bringing this to our attention! I will put in a PR to fix this.

**Comment by mksamelson** [comment]
How long does that normally take you guys?

**Comment by jackmoody11** [comment]
Just put in the PR @mksamelson. Hopefully it will be a quick review for @coyo8 and we can get that squared away. Thanks again!

**Comment by jackmoody11** [comment]
If you are using 0.1.5, I am assuming you cloned the latest repo from GitHub? If you want to fix it on your own you can see the small change I made in #90. This should add support for 8-k forms.

**Comment by mksamelson** [comment]
Thank you!
