### ISSUE TITLE
Announcement Date / Filing Date

### ISSUE THREAD

**Issue by mksamelson** [coyo8/sec-edgar#92]
The date the company _announced_ results is very important.  That is the date the results become public as opposed to the statement date which is the date the company closes the books.

You should include announcement/filing date with each statement.

**Comment by jackmoody11** [comment]
@mksamelson I believe we are using the filing date (dateb should be the same thing as if you use the prior to search bar in SEC EDGAR company search). See the prior to search bar [here, for example.](https://www.sec.gov/cgi-bin/browse-edgar?CIK=aapl&owner=exclude&action=getcompany)

**Comment by mksamelson** [comment]
10Qs appear to have the close of period date.

**Comment by jackmoody11** [comment]
@mksamelson How would you get the announcement day from the EDGAR database if you were searching normally?

**Comment by mksamelson** [comment]
I have to look.  It is the same thing as filing date I believe.

**Comment by mksamelson** [comment]
I will come back to you on it.

**Comment by mksamelson** [comment]
You are correct.  There is no announcement date associated with 10Q/10K filing.  I erroneously believed the filing date was always the filing date.  It is not (sometimes it is).

Announcement Date (earnings announcement date) actually comes via an 8 k and can be anywhere between 0 to a few days before the actual filing date.

Sorry for the confusion.  However, if you _are_  able to pluck the announcement date and add it to the filings it would be very useful

**Comment by jackmoody11** [comment]
Right now this doesn't seem to be in the scope of the project. We still haven't decided if it is best to make a parser a part of the project or not (right now, the project's main goal is fetching the filings). If you think this is something that the project should have, feel free to leave a comment and I will reopen this issue. Thanks!
