### ISSUE TITLE
No filings available for NPORT

### ISSUE THREAD

**Issue by mjkoo91** [coyo8/sec-edgar#99]
When using the commands below, I receive a "ValueError: No filings available." output however other filing types work without any issues such as FilingType.FILING_NCEN.

my_filings = Filing(cik=my_cik, filing_type=FilingType.FILING_NPORT, count=15)
my_filings.save('~/tempdir')

Perhaps there is a difference between Edgar and your variable definition for NPORT? It seems that your code defines it as 'n-port' but the filter on Edgar seems to be 'nport-p'? I apologize if this is not the root cause of the issue but your assistance with finding why no filings are available for nport-p is much appreciated. Thank you for your valuable time and continual support.

**Comment by jackmoody11** [comment]
@mjkoo91 thanks for bringing this to our attention! I think this should be a simple fix. We just need to change the value for the enum. I’ll tag you when this is fixed.

**Comment by mjkoo91** [comment]
@jackmoody11 Thank you very much for your quick response. I will look forward to your quick fix! Thanks again. :)

**Comment by jackmoody11** [comment]
@mjkoo91 what company/fund were you interested in? This will help with testing.

**Comment by mjkoo91** [comment]
@jackmoody11  One of the funds that I'm interested in is 'AB BOND FUND, INC.' (CIK= 0000003794) which has 13 NPORT-P Filings. Please let me know if there is any other information you may be interested in. Thank you.
